### ISSUE TITLE
pages - Editor Bugs

### ISSUE THREAD

**Issue by wightmike** [eflip/LittlefootCMS#194] opened 2017-04-14 00:37 UTC
* There is no visible cursor
* What's going on with the line numbers?

**Comment by bioshazard** [comment] 2017-04-16 00:42
This is a bug caused by an incompatibility with LFCSS. 

When I inspect element and open `<head>` and rightclick>delete the `<link rel="stylesheet" href="http://dev5.bioshazard.com/littlefoot/lf/system/lib/lf.css" />` element that includes `lf.css`, there is no cursor problem.

![image](https://cloud.githubusercontent.com/assets/5616668/25067779/f3424e78-221b-11e7-8faa-503a19c9dd74.png)

Assigning to you for review.

**Comment by wightmike** [comment] 2017-04-18 03:41
border: 0; on the css reset caused this problem.

moved div to its own line resetting everything but border:

```
.lf div {
	margin: 0;
	padding: 0;
	vertical-align: baseline;
}
```

https://github.com/lfcms/LittlefootCMS/pull/207

**Closed as completed** 2017-04-18 03:41 UTC
Labels: bug, style
